# HMMs are probabilistic generative models, in which a sequence of observable variables 𝐎
#  is generated by a sequence of internal hidden states 𝐙
# . The hidden states are not observed directly. The transitions between hidden states are assumed to have the form of a (first-order) Markov chain. They can be specified by the start probability vector 𝝅
#  and a transition probability matrix 𝐀
# . The emission probability of an observable can be any distribution with parameters 𝐁
#  conditioned on the current hidden state. The HMM is completely determined by 𝝀=(𝝅,𝐀,𝐁)
# .
# In order to have a useful HMM model for a real application, there are three basic problems that must be solved:
#
# Problem 1 (Likelihood): Given an HMM 𝝀=(𝝅,𝐀,𝐁)
#  and an observation sequence 𝐎
# , determine the likelihood 𝑃(𝐎|𝝀)
# Problem 2 (Decoding): Given an observation sequence 𝐎
#  and an HMM 𝝀=(𝝅,𝐀,𝐁)
# , discover the best hidden state sequence 𝐙
# Problem 3 (Learning): Given an observation sequence 𝐎
#  and the set of states in the HMM, learn the HMM parameters 𝝀

# We only have 3 states so 3 probabilites.
import numpy as np
import polars as pl

# Consts
REGIMES = ["bull", "bear", "kangaroo"]
BULL, BEAR, KANGAROO = 0, 1, 2
# List of vectors is a matrix
# The diagonal is the P that a regime STAYS in a regime, so mean dwell = 1/(1-a_ii):
# bull 100 steps (trends are long), bear 28.6 (crashes are short and sharp),
# kangaroo 35.7. Off-diagonals route trends through chop rather than flipping
# bull <-> bear directly, and chop resolves upward more often than down.
A = np.array([[0.990, 0.002, 0.008],
              [0.005, 0.965, 0.030],
              [0.020, 0.008, 0.972]])
# Ensure every row sums to 1
assert np.allclose(A.sum(axis=1), 1), "Rows of A do not sum to 1"

# Stationary distribution -- the long-run share of time spent in each regime.
# Left eigenvector of A for eigenvalue 1.
_w, _v = np.linalg.eig(A.T)
PI = np.real(_v[:, np.argmin(np.abs(_w - 1))])
PI = PI / PI.sum()
assert np.allclose(PI @ A, PI) and (PI > 0).all()
# In regards to B -> For each of the 3 states you need whatever your AR(1) needs: a persistence coefficient φ, 
# a shock scale σ, a drift μ, and whatever governs your other channels. We need one AR(1) per regime.
# Channel 1 — log returns
B = {
    BULL:     {"phi":  0.05, "sigma": 0.008, "mu":  0.0006},
    BEAR:     {"phi":  0.35, "sigma": 0.022, "mu": -0.0010},
    KANGAROO: {"phi": -0.30, "sigma": 0.022, "mu":  0.0000},
}

# Channel 3 — log volume (regime-dependent)
B_VOL = {
    BULL:     {"phi": 0.85, "sigma": 0.25, "mu": 0.00},
    BEAR:     {"phi": 0.85, "sigma": 0.40, "mu": 0.55},
    KANGAROO: {"phi": 0.85, "sigma": 0.40, "mu": 0.35},
}
# Channel 4 — slow drift (regime-independent, single dict, no state lookup)
B_SLOW = {"phi": 0.99, "sigma": 0.10, "mu": 0.0}

# T=20k daily bars is ~80 years. Much longer and the cumulative log price runs away:
# at any realistic per-step drift, 200k steps compounds to e^54, which is not a market.
T = 20_000

# 1. Sample the state path. Loop T steps. At each, draw the next state from the current state's row of A.
# The tool is np.random.Generator.choice with p=A[s] — and use a seeded default_rng, not the legacy global functions, so runs are reproducible.
# Output: an integer array of length T.

# Outside the loop so that the rng is not replaced on each loop
rng = np.random.default_rng(0) # With this seed it is reproducible
# Draw the initial state from the stationary distribution rather than pinning it to
# BULL. Starting in a fixed state means the chain needs hundreds of steps to mix, and
# burn-in would have to absorb that on top of the AR(1) transients.
s = rng.choice(3, p=PI)
# We need a container to put the regime states at each t
# I will just use a simple list
regime_ts = []
for t in range(T):
    # We get BULL let's say then set s = BULL again (0)
    s = rng.choice(3, p=A[s]) # s is the sample? It's the state
    regime_ts.append(s)

assert len(regime_ts) == T, f"Regime timeseries length {len(regime_ts)} != number of steps specified ({T})"
regime_ts = np.array(regime_ts, dtype=np.int64)
# 2. Run the AR(1) along that path. Sequential loop, since each step needs the previous value.
# Look up B[state], apply the recurrence, store. This is the one part you can't vectorize.
# 200k steps in a Python loop is fine — under a second.
# I need to run an AR(1) model on this data. I need the current step's value and the previous one
ret_prev = 0
log_vol_prev = 0
slow_prev = 0
log_rets = []
log_vols = []
slows = []
for regime in regime_ts:
    # One INDEPENDENT shock per channel. A single shared eps would make every
    # channel a deterministic function of the same draw, and the model would
    # solve the task by isolating that one factor instead of learning regimes.
    eps_ret, eps_vol, eps_slow = rng.standard_normal(3)
    ret_state = B[int(regime)]
    log_vol_state = B_VOL[int(regime)]
    # Rets -- Channel 1
    log_ret_t = ret_state["mu"] + ret_state["phi"]*(ret_prev - ret_state["mu"]) + ret_state["sigma"]*eps_ret
    # Log vol -- Channel 3
    log_vol_t = log_vol_state["mu"] + log_vol_state["phi"]*(log_vol_prev - log_vol_state["mu"]) + log_vol_state["sigma"]*eps_vol
    # Slow factor -- Channel 4
    slow_t = B_SLOW["mu"] + B_SLOW["phi"]*(slow_prev - B_SLOW["mu"]) + B_SLOW["sigma"]*eps_slow

    # Set previous values for all AR(1)s
    ret_prev = log_ret_t
    log_vol_prev = log_vol_t
    slow_prev = slow_t

    # Add all data per pass to the lists
    log_rets.append(log_ret_t)
    log_vols.append(log_vol_t)
    slows.append(slow_t)



# 3. Derive the remaining channels. Realized vol is a rolling std over the returns.
# Stack everything into a (T, 4) frame: log_ret | realized_vol | log_vol | slow.
VOL_WINDOW = 20

df = pl.DataFrame(
    {
        "log_ret": log_rets,
        "log_vol": log_vols,
        "slow": slows,
    }
).with_columns(
    # Channel 2 -- realized vol, rolling std of the log returns.
    # The first VOL_WINDOW-1 rows are null; burn-in (step 4) drops them.
    pl.col("log_ret").rolling_std(window_size=VOL_WINDOW).alias("realized_vol")
).select(["log_ret", "realized_vol", "log_vol", "slow"])

assert df.shape == (T, 4), f"Expected a ({T}, 4) frame, got {df.shape}"



CHANNELS = ["log_ret", "realized_vol", "log_vol", "slow"]

# 4. Discard burn-in and validate. Drop the first ~2000 steps, then check the generator
# actually produced what the parameters say it should. Every downstream result is
# meaningless if the generator is wrong, and this is the cheapest place to catch it.
BURN_IN = 500   # 5 time constants of the slowest AR(1) (B_SLOW, phi=0.99), and >> VOL_WINDOW

data = df.slice(BURN_IN).to_numpy()          # (N, 4), float64
labels = regime_ts[BURN_IN:]                  # (N,)
N = data.shape[0]
assert data.shape == (T - BURN_IN, 4)
assert not np.isnan(data).any(), "NaNs survived burn-in -- is BURN_IN >= VOL_WINDOW?"
assert len(labels) == N

log_ret = data[:, CHANNELS.index("log_ret")]
realized_vol = data[:, CHANNELS.index("realized_vol")]

def report_generator_checks() -> None:
    """Step 4 validation output. Called only when this module is run as a script."""
    print(f"After burn-in: {N:,} steps, {data.shape[1]} channels")
    print(f"{'regime':<10}{'share':>8}{'pi':>8}{'mean rv':>10}{'sigma':>8}{'ar1':>8}{'phi':>8}")
    for k, name in enumerate(REGIMES):
        in_k = labels == k
        # Lag-1 autocorrelation, measured only on consecutive pairs that stay in
        # regime k, so transitions don't contaminate the estimate.
        pair = in_k[:-1] & in_k[1:]
        ar1 = np.corrcoef(log_ret[:-1][pair], log_ret[1:][pair])[0, 1]
        print(f"{name:<10}{in_k.mean():>8.3f}{PI[k]:>8.3f}{realized_vol[in_k].mean():>10.4f}"
              f"{B[k]['sigma']:>8.3f}{ar1:>8.3f}{B[k]['phi']:>8.3f}")
    log_price = np.cumsum(log_ret)
    print(f"log price: end={log_price[-1]:+.2f} (price x{np.exp(log_price[-1]):.1f})  "
          f"min={log_price.min():+.2f}  max={log_price.max():+.2f}")
    print("channel corr (log_ret vs log_vol, log_ret vs slow): "
          f"{corr[0, 2]:.4f}, {corr[0, 3]:.4f}")


# Independence check: the channels must not be driven by one shared shock.
# This assert stays at module level -- it must fire on import, not just as a script.
corr = np.corrcoef(data, rowvar=False)
assert abs(corr[0, 2]) < 0.05 and abs(corr[0, 3]) < 0.05, \
    "Channels are near-collinear -- are the AR(1)s sharing an eps draw?"


# 5. Standardize, fit on TRAIN ONLY. Channels have wildly different scales
# (returns ~0.01, log volume ~0.7). Computing mean/std on the full series is a leak
# you would never notice in the loss curve.
WINDOW = 64
GAP = 64          # windows dropped between the two splits
TRAIN_FRAC = 0.70

n_train_rows = int(TRAIN_FRAC * N)
mu = data[:n_train_rows].mean(axis=0)
sd = data[:n_train_rows].std(axis=0)
assert (sd > 0).all()
data_std = (data - mu) / sd

# 6. Window it. sliding_window_view is a view, no copy: (N-WINDOW+1, 4, WINDOW),
# transposed to the (n_windows, WINDOW, 4) layout the model wants.
# The label of a window is the state at its FINAL timestep.
windows = np.lib.stride_tricks.sliding_window_view(data_std, WINDOW, axis=0)
windows = windows.transpose(0, 2, 1)
window_labels = labels[WINDOW - 1:]
n_windows = windows.shape[0]
assert windows.shape == (N - WINDOW + 1, WINDOW, 4)
assert len(window_labels) == n_windows

# 7. Split by time with a gap. Window i covers timesteps [i, i+WINDOW).
# The last train window must end before n_train_rows, and the first test window
# starts GAP windows after that, so no test window shares a timestep with a
# training window -- and there is a real buffer on top.
train_end = n_train_rows - WINDOW          # inclusive last train window index
test_start = train_end + WINDOW + GAP      # first test window index

X_train, y_train = windows[: train_end + 1], window_labels[: train_end + 1]
X_test, y_test = windows[test_start:], window_labels[test_start:]

# No shared timesteps: last train window ends at train_end+WINDOW-1, first test starts at test_start.
assert test_start > train_end + WINDOW - 1
assert test_start - (train_end + 1) >= GAP, "Fewer than GAP windows dropped between splits"

if __name__ == "__main__":
    report_generator_checks()
    print(f"windows: {n_windows:,} total  train={len(X_train):,}  "
          f"dropped={test_start - train_end - 1:,}  test={len(X_test):,}")
    print(f"train label shares: {np.bincount(y_train, minlength=3) / len(y_train)}")
    print(f"test  label shares: {np.bincount(y_test, minlength=3) / len(y_test)}")
