"""Baselines and probes for the JEPA smoke test.

H0: a JEPA trained with VICReg does not meaningfully explain more than a simple
logistic regression on a raw flattened window.

Everything here is a *frozen-representation linear probe* on the same time-held-out
test split, so the numbers are directly comparable. The point of the file is the
controls, not the JEPA: a self-supervised smoke test that only compares against
chance will happily report success on a representation that is worse than the raw
input.

Why bear-vs-kangaroo gets its own column
----------------------------------------
The two regimes are deliberately built to be near-identical in amplitude and to
differ almost entirely in TIME STRUCTURE:

    regime      sigma (returns)   phi (lag-1 autocorr)   log-vol mean
    bear        0.022             +0.35                  0.55
    kangaroo    0.022             -0.30                  0.35

Their return volatility is IDENTICAL, so nothing that reads amplitude alone can
tell them apart -- the separating signal is the sign of the lag-1 autocorrelation,
which requires modelling how consecutive timesteps relate. Overall accuracy is a
poor diagnostic because bull is 58% of the data and is easy (its sigma is 2.75x
lower), so a model can score well while being blind to temporal structure.

One honest caveat: the separation is not *purely* temporal. The log-volume channel
has different means for bear (0.55) and kangaroo (0.35), which leaks a weak
amplitude-only signal. The `window-mean` baseline below exists to quantify exactly
how much of the bear/kangaroo gap is available without any temporal modelling, so
the temporal claim can be checked rather than assumed.
"""

from __future__ import annotations

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from .HMM_data import REGIMES, X_test, X_train, y_test, y_train

BULL, BEAR, KANGAROO = 0, 1, 2
SEED = 0


# --------------------------------------------------------------------------
# Metrics
# --------------------------------------------------------------------------
def evaluate(proba: np.ndarray, y: np.ndarray) -> dict[str, float]:
    """Overall accuracy plus the bear-vs-kangaroo discrimination.

    The second number restricts to test windows that are truly bear or kangaroo
    and asks the model to choose between just those two, so bull -- the easy,
    majority class -- cannot inflate it.
    """
    pred = proba.argmax(1)
    bk = (y == BEAR) | (y == KANGAROO)
    two = proba[bk][:, [BEAR, KANGAROO]]
    bk_pred = np.where(two.argmax(1) == 0, BEAR, KANGAROO)
    return {
        "acc": float((pred == y).mean()),
        "bear_vs_kang": float((bk_pred == y[bk]).mean()),
    }


def probe(Z_train: np.ndarray, Z_test: np.ndarray) -> dict[str, float]:
    """Multinomial logistic regression on a frozen representation.

    Fit on train only; the scaler is inside the pipeline so it never sees test.
    """
    clf = make_pipeline(
        StandardScaler(),
        LogisticRegression(max_iter=5000, random_state=SEED),
    ).fit(Z_train, y_train)
    return evaluate(clf.predict_proba(Z_test), y_test)


# --------------------------------------------------------------------------
# Hand-built feature baselines
# --------------------------------------------------------------------------
def window_features(X: np.ndarray) -> dict[str, np.ndarray]:
    """Cheap summaries of a (N, 64, 4) batch of windows."""
    r = X[:, :, 0]  # standardized log returns
    mu, sd = r.mean(1), r.std(1)
    lag1 = ((r[:, :-1] - mu[:, None]) * (r[:, 1:] - mu[:, None])).mean(1) / (sd**2 + 1e-9)
    return {
        # Amplitude only: per-channel means. Deliberately contains NO temporal
        # information -- it is the control for the bear-vs-kangaroo claim.
        "window-mean": X.mean(1),
        "vol only": sd[:, None],
        "vol + lag1 autocorr": np.c_[sd, lag1],
        "mean + vol + autocorr": np.c_[mu, sd, lag1],
        # The H0 bar: a linear model on the untransformed window.
        "raw flattened window": X.reshape(len(X), -1),
    }


# --------------------------------------------------------------------------
# HMM baseline
# --------------------------------------------------------------------------
def hmm_baselines() -> dict[str, dict[str, float]]:
    """Fit a 3-state Gaussian HMM on the training timesteps.

    This is the strongest principled baseline: the data really was generated by a
    3-state Markov chain, so the HMM has the right state structure. What it does
    NOT have is any model of within-regime autocorrelation -- a Gaussian HMM
    treats observations as conditionally independent given the state. It can
    therefore only separate bear from kangaroo using the weak log-volume mean
    offset, not the sign of phi.

    Two variants are reported because they sit in different information regimes:
      - windowed  : forward algorithm over each 64-step window in isolation,
                    posterior at the FINAL step. Causal, and directly comparable
                    to every other row in the table.
      - full-Viterbi : Viterbi over the entire test sequence at once. Uses future
                    information and unlimited context, so it is NOT comparable --
                    it is included only as a rough ceiling.
    """
    from hmmlearn.hmm import GaussianHMM

    # Reconstruct the per-timestep series each split's windows were cut from.
    # Window i is rows [i, i+64); stacking the first column of each window plus
    # the tail of the last window recovers the contiguous series exactly.
    def series(X: np.ndarray) -> np.ndarray:
        return np.vstack([X[:, 0, :], X[-1, 1:, :]])

    tr, te = series(X_train), series(X_test)

    model = GaussianHMM(
        n_components=3, covariance_type="full", n_iter=200, random_state=SEED
    ).fit(tr)

    # HMM states are arbitrary labels. Align them to the true regimes using the
    # TRAIN split only -- doing this on test would leak.
    from itertools import permutations

    tr_states = model.predict(tr)
    tr_true = y_train  # label of window i is the state at its FINAL timestep
    # window i's final timestep is series index i+63
    idx = np.arange(len(y_train)) + 63
    best, best_acc = None, -1.0
    for p in permutations(range(3)):
        mapped = np.array(p)[tr_states[idx]]
        a = (mapped == tr_true).mean()
        if a > best_acc:
            best, best_acc = np.array(p), a

    results = {}

    # --- windowed (causal, comparable) ---
    # Forward-algorithm posterior at the last step of each window, done in one
    # batched pass rather than 5723 separate hmmlearn calls.
    logprob_obs = np.array(
        [model._compute_log_likelihood(te[i : i + 1]) for i in range(len(te))]
    ).squeeze(1)  # (T, 3)
    log_A = np.log(model.transmat_ + 1e-300)
    log_pi = np.log(model.startprob_ + 1e-300)

    from scipy.special import logsumexp

    n_win = len(y_test)
    post = np.empty((n_win, 3))
    for w in range(n_win):
        a = log_pi + logprob_obs[w]
        for t in range(w + 1, w + 64):
            a = logsumexp(a[:, None] + log_A, axis=0) + logprob_obs[t]
        post[w] = a - logsumexp(a)
    proba_win = np.exp(post)[:, np.argsort(best)]
    results["HMM (windowed, causal)"] = evaluate(proba_win, y_test)

    # --- full-sequence Viterbi (advantaged, NOT comparable) ---
    te_states = best[model.predict(te)]
    pred_full = te_states[np.arange(n_win) + 63]
    onehot = np.eye(3)[pred_full]
    results["HMM (full Viterbi, non-causal)"] = evaluate(onehot, y_test)

    return results


# --------------------------------------------------------------------------
# Report
# --------------------------------------------------------------------------
def run(include_jepa: bool = True) -> dict[str, dict[str, float]]:
    rows: dict[str, dict[str, float]] = {}

    # Chance: always predict the majority class. For bear-vs-kangaroo, chance is
    # the larger of the two subset shares.
    shares = np.bincount(y_test, minlength=3) / len(y_test)
    bk = (y_test == BEAR) | (y_test == KANGAROO)
    bk_share = np.bincount(y_test[bk], minlength=3)[[BEAR, KANGAROO]] / bk.sum()
    rows["majority class (chance)"] = {
        "acc": float(shares.max()),
        "bear_vs_kang": float(bk_share.max()),
    }

    ftr, fte = window_features(X_train), window_features(X_test)
    for name in ftr:
        rows[name] = probe(ftr[name], fte[name])

    rows.update(hmm_baselines())

    if include_jepa:
        from .jepa import build_encoder, embed, train_jepa

        # Null control: identical architecture, never trained. If the trained
        # encoder cannot beat this, the training did nothing.
        rnd = build_encoder(seed=SEED)
        rows["random-init encoder (null)"] = probe(
            embed(rnd, X_train), embed(rnd, X_test)
        )

        enc, _ = train_jepa(seed=SEED, verbose=True)
        rows["JEPA + VICReg (trained)"] = probe(embed(enc, X_train), embed(enc, X_test))

    return rows


def print_table(rows: dict[str, dict[str, float]]) -> None:
    print(f"\n{'representation':<34}{'test acc':>10}{'bear vs kang':>14}")
    print("-" * 58)
    for k, v in rows.items():
        print(f"{k:<34}{v['acc']:>10.3f}{v['bear_vs_kang']:>14.3f}")


if __name__ == "__main__":
    print_table(run(include_jepa=True))
